swagger: '2.0'
info:
  version: 0.1.0
  title: Simple To Do List API
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
paths:
  /:
    get:
      tags: ["todos"]
      operationId: find
      parameters:
        - name: limit
          in: formData
          type: integer
          format: int64
          required: true
          allowEmptyValue: true
        - name: "X-Rate-Limit"
          in: header
          type: integer
          format: int64
          required: true
        - name: words
          in: formData
          type: array
          collectionFormat: multi
          allowEmptyValue: true
          items:
            type: string
          required: true
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/item"
        404:
          description: Not Found
          schema:
            $ref: "#/definitions/error"
        500:
          description: Internal Error
          schema:
            $ref: "#/definitions/error"
    post:
      tags: ["todos"]
      operationId: addOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/item"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/item"
        500:
          description: Internal Error
          schema:
            $ref: "#/definitions/error"
  /{id}:
    parameters:
      - type: integer
        format: int64
        name: id
        in: path
        required: true
    put:
      tags: ["todos"]
      operationId: updateOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/item"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/item"
        404:
          description: Not Found
          schema:
            $ref: "#/definitions/error"
        500:
          description: Internal Error
          schema:
            $ref: "#/definitions/error"
    delete:
      tags: ["todos"]
      operationId: destroyOne
      responses:
        204:
          description: Deleted
        404:
          description: Not Found
          schema:
            $ref: "#/definitions/error"
        500:
          description: Internal Error
          schema:
            $ref: "#/definitions/error"
definitions:
  item:
    type: object
    required:
      - description
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      description:
        type: string
        minLength: 1
      completed:
        type: boolean
  error:
    type: object
    properties:
      code:
        type: string
        x-nullable: false
      message:
        type: string
        x-nullable: false
      attributes:
        type: object
        additionalProperties:
          type: string
        x-nullable: false